### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by sgmullins** [nordicgiant2/react-nice-resume#2]
Good job on the library! Super fun to play with. Were you able to get the contact form hooked up and  able to send out emails? I have hit a road block and not sure what else to try.
Thanks again!

**Comment by lindelof** [comment]
What problems did you encounter? Can you elaborate?

**Comment by MerlinOfCode** [comment]
There doesn't seem to be any logic to send the emails.

**Comment by LeSauvage** [comment]
Any code sample for the /inc/sendEmail.php ?

**Comment by MerlinOfCode** [comment]
I ended up creating a script that works for email.js if you want that.
